name: karaoke-maker
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2020.12.5=ha878542_0
  - certifi=2020.12.5=py38h578d9bd_1
  - ffmpeg=4.3.1=hca11adc_2
  - freetype=2.10.4=h0708190_1
  - gettext=0.19.8.1=h0b5b191_1005
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - lame=3.100=h7f98852_1001
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - libffi=3.3=h58526e2_2
  - libflac=1.3.3=h9c3ff4c_1
  - libgcc-ng=9.3.0=h2828fa1_19
  - libgomp=9.3.0=h2828fa1_19
  - libogg=1.3.4=h7f98852_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libsndfile=1.0.31=h9c3ff4c_1
  - libstdcxx-ng=9.3.0=h6de172a_19
  - libvorbis=1.3.7=h9c3ff4c_0
  - ncurses=6.2=h58526e2_4
  - nettle=3.6=he412f7d_0
  - openh264=2.1.1=h780b84a_0
  - openssl=1.1.1k=h7f98852_0
  - pip=21.1=pyhd8ed1ab_0
  - python=3.8.8=hffdb5ce_0_cpython
  - python_abi=3.8=1_cp38
  - readline=8.1=h46c0cb4_0
  - setuptools=49.6.0=py38h578d9bd_3
  - sqlite=3.35.5=h74cdb3f_0
  - tk=8.6.10=h21135ba_1
  - wheel=0.36.2=pyhd3deb0d_0
  - x264=1!161.3030=h7f98852_0
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h516909a_1010
  - pip:
    - absl-py==0.12.0
    - astunparse==1.6.3
    - audioread==2.1.9
    - cachetools==4.2.1
    - cffi==1.14.5
    - chardet==4.0.0
    - click==7.1.2
    - decorator==5.0.7
    - ffmpeg-python==0.2.0
    - future==0.18.2
    - gast==0.3.3
    - google-auth==1.29.0
    - google-auth-oauthlib==0.4.4
    - google-pasta==0.2.0
    - grpcio==1.37.0
    - h11==0.12.0
    - h2==3.2.0
    - h5py==2.10.0
    - hpack==3.0.0
    - httpcore==0.12.3
    - httpx==0.16.1
    - hyperframe==5.2.0
    - idna==2.10
    - joblib==1.0.1
    - keras-preprocessing==1.1.2
    - librosa==0.8.0
    - llvmlite==0.36.0
    - markdown==3.3.4
    - norbert==0.2.1
    - numba==0.53.1
    - numpy==1.18.5
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - packaging==20.9
    - pandas==1.1.2
    - pooch==1.3.0
    - protobuf==3.15.8
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2021.1
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - resampy==0.2.2
    - rfc3986==1.4.0
    - rsa==4.7.2
    - scikit-learn==0.24.1
    - scipy==1.4.1
    - six==1.15.0
    - sniffio==1.2.0
    - soundfile==0.10.3.post1
    - spleeter==2.2.2
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.0
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.3.0
    - tensorflow-estimator==2.3.0
    - termcolor==1.1.0
    - threadpoolctl==2.1.0
    - typer==0.3.2
    - urllib3==1.26.4
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - youtube-dl==2021.4.17
